# Generated by Django 2.1.7 on 2019-05-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': '班级管理',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': '学院管理',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '评论管理',
            },
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': '宿舍管理',
            },
        ),
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '帖子管理',
            },
        ),
        migrations.CreateModel(
            name='PublicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '信息公示管理',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('province', models.CharField(max_length=10, verbose_name='省份')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证')),
                ('class_stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.Class', verbose_name='班级')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.College', verbose_name='学院')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.Dormitory', verbose_name='宿舍')),
            ],
            options={
                'verbose_name_plural': '学生管理',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '测试',
            },
        ),
        migrations.CreateModel(
            name='YearCheckInData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True)),
                ('checked', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.Student')),
            ],
            options={
                'verbose_name_plural': '签到数据管理',
            },
        ),
        migrations.CreateModel(
            name='YearCheckInEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('student', models.ManyToManyField(through='Share.YearCheckInData', to='Share.Student')),
            ],
            options={
                'verbose_name_plural': '签到事件管理',
            },
        ),
        migrations.AddField(
            model_name='yearcheckindata',
            name='year_check_in_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.YearCheckInEvent'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.Student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.PostCard'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.College'),
        ),
    ]
