# Generated by Django 2.1.7 on 2019-05-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearcheckindata',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
